[package]
name = "wsl-stream-cleaner"
version = "0.1.0"
authors = ["Georg Echterling <georg@echterling.net>"]
edition = "2018"
publish = false

[dependencies]
notify = "4.0.15"
log = "0.4.8"
env_logger = "0.7.1"
dotenv = "0.15.0"